gamma: 0.9
n_iter: 100
learning_rate: 0.01
reward_to_go: True
normalize_advantages: True
seed: 9
n_experiments: 1
nn_baseline: True
n_layers: 2
size: 32
max_path_length: 800
min_timesteps_per_batch: 8000
num_target_updates: 10
num_grad_steps_per_target_update: 10

distance_thresh: 0.01
vel_limit: 0.4
vel_mode: "raw"
max_training_goals: 2
goal_XYZs: [[[-0.583, -0.468, 0.281], [-0.611, -0.476, 0.284], [-0.604, -0.505, 0.285]], [[0.196, -0.199, 0.269], [0.226, -0.193, 0.268], [0.220, -0.164, 0.265]]]

obj_x1: 0.015
obj_y1: 0.015
obj_z1: 0.14
obj_x2: 0.015
obj_y2: -0.015
obj_z2: 0.14
obj_x3: -0.015
obj_y3: -0.015
obj_z3: 0.14

cmd_names:  ['right_j3', 'right_j4', 'right_j5']
cmd_mode: "VELOCITY_MODE"
initial-position: [1.59, -3.0, 1.59, 0.0, 0.0, 0.0, 0.0, 0.0]
jnt_init_limits: [[-0.1, 0.1], [-0.1, 0.1], [-0.1, 0.1]]
jnt_pos_limits: [[-2.2, 2.2], [-2.5, 2.5], [-2.2, 2.2]]

jnt_obs_dim: 3
act_dim:  3
goal_obs_dim: 18
jnt_indices: [3, 4, 5]
debug_lvl: "All"
